# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
print(A)
print()

print(A.shape)  # shape of the matrix
print()

print(A.size)  # size of the matrix
print()

print(type(A))  # datatype of the matrix
print()

print(A.ndim)  # dimension of the matrix(no of axis)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

(3, 5)

15

<class 'numpy.ndarray'>

2


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)
print()
print(B-C)  # Elementwise subtraction
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]



In [5]:
print(B*C)  # Normal multiplication (elementwise multiplication)
print()

print(B@C)  # Matrix multiplication
print()

print(B.dot(C))  # Matrix multiplication by another way
print()

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]



### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(B.sum(axis=0))  # sum of each column
print()
print(B.sum(axis=1))  # sum of each row
print()

print(B.min(axis=0))  # minimum of each column
print()
print(B.min(axis=1)) # minimum of each row
print()

print(B.sum())  # total sum
print()
print(B.min())  # min in whole matrix
print()

print(B.max())  # max in whole matrix
print()
print(B.max(axis=0))  # maximum of each column
print()
print(B.max(axis=1))  # maximum of each row

[12 15 18]

[ 6 15 24]

[1 2 3]

[1 4 7]

45

1

9

[7 8 9]

[3 6 9]


In [8]:
print(B)
print()
print(np.exp(B))
print()

print(np.argmin(B))
print()
print(np.argmin(B, axis=1))
print()

print(B.mean(axis=0))  # mean of each column
print()
print(np.median(B, axis=0))  # median of each column

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

0

[0 0 0]

[4. 5. 6.]

[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [9]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

When you give only one index in slicing , it will execute all the remaining values if the other index is missing. 

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [11]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [13]:
for i in A.flat:   # elementwise iteration
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [14]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Variable a gives series of numbers until 29 and variable b gives two matrices which has 3 rows and appropriate columns 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [15]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

print(m1.size, m1.shape)
print(m2.size, m2.shape)

[[2 3]
 [4 5]]
4 (2, 2)
2 (2,)


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [16]:
v1 = np.array([1, 2, 3])

print(v1)
print(v1 + 1)

[1 2 3]
[2 3 4]


In [17]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [18]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print()

print(B)
print()
print(C)
print()

print(D)
print()
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]

[[ 4 -2  1]
 [ 2 -4 -2]]

[[1 2]
 [2 1]]

[[3 4]
 [4 3]]

[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [19]:
def add_mult_matrices(A, B, add_or_multiply):
    
    if not (isinstance(A, np.ndarray) and isinstance(B, np.ndarray)):
        raise Exception ('Please provide two matrices')
        
    if add_or_multiply == 'add':
        if not A.shape == B.shape:
            raise ValueError('Shape of the two matrices is not equal')
        else:
            return A + B
        
    elif add_or_multiply == 'multiply':
        if not A.shape[1] == B.shape[0]:
            raise ValueError('number of rows in first matrix is not equal to number columns in second matrix')
        else:
            return A @ B
        
    else:
        raise Exception('add_or_multiply argument must be either "add" or "multiply".')
        
    

In [20]:
print(add_mult_matrices(B, -2*A, 'add'))  # adding two same shape matrices 
print()

print(add_mult_matrices(3*C, -E, 'add'))  # adding two different shape matrices
print()

[[ 0 -4  3]
 [ 0 -2 -4]]



ValueError: Shape of the two matrices is not equal

In [21]:
print(add_mult_matrices(A, C, 'multiply'))  # matrix multiplying by giving inappropriate matrices
print()

ValueError: number of rows in first matrix is not equal to number columns in second matrix

In [22]:
print(add_mult_matrices(C, D, 'multiply'))  # matrix multiplying by giving appropriate matrices
print()

print(add_mult_matrices(C, B, 'multiply'))  # matrix multiplying by giving appropriate matrices
print()

[[11 10]
 [10 11]]

[[  8 -10  -3]
 [ 10  -8   0]]



**Chap2. Question 2**

In [23]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])

C = np.array([[4, 3], [0, 2]])

print(A)
print()

print(B)
print()
print(C)

[[1 2]
 [2 4]]

[[2 1]
 [1 3]]

[[4 3]
 [0 2]]


In [24]:
AB = print(add_mult_matrices(A, B, 'multiply'))
print()
AC = print(add_mult_matrices(A, C, 'multiply'))
print()

print(AB==AC)
print()
print(B==C)

[[ 4  7]
 [ 8 14]]

[[ 4  7]
 [ 8 14]]

True

[[False False]
 [False False]]


**Chap2. Question 3**

In [25]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

print(A)
print()
print(D)

[[1 1 1]
 [1 2 3]
 [1 3 4]]

[[2 0 0]
 [0 3 0]
 [0 0 4]]


In [26]:
print(add_mult_matrices(A, D, 'multiply'))
print()
print(add_mult_matrices(D, A, 'multiply'))

[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]

[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [27]:
A = np.array([[1, -1], [-1, 1]])
B = np.array([[-1, 1], [1, -1]])

print(add_mult_matrices(A, B, 'multiply'))

[[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [28]:
A = np.array([[5, 6], [4, 5]])
B = np.array([[6, 4], [3, 3]])

print(A)
print()
print(B)
print()

print(np.linalg.inv(A))  # inversing the matrix A (2x2)
print()
print(np.linalg.inv(B))  # inversing the matrix B (2x2)
      

[[5 6]
 [4 5]]

[[6 4]
 [3 3]]

[[ 5. -6.]
 [-4.  5.]]

[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3**

In [29]:
C = np.array([[2, 2], [1, 2]])

print(np.linalg.inv(C))  # inversing the matrix C (2x2)

[[ 1.  -1. ]
 [-0.5  1. ]]


**Chap10. Question 1 a)**

In [30]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
B = np.array([-7, 5, 2])
              
print(A)
print()
print(B)
              
print()    
print(np.linalg.solve(A,B))  # solving the linear algebra equation through Ax=B 

[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]

[-7  5  2]

[ 3.  4. -6.]


**Chap10. Question 1 b)**

In [31]:
A = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
B = np.array([1, -1, 1])

print(A)
print()
print(B)
print()

print(np.linalg.solve(A,B))  # solving the linear algebra equation through Ax=B 

[[ 1 -2  3]
 [-1  3 -1]
 [ 2 -5  5]]

[ 1 -1  1]

[ 8.  2. -1.]


**Chap 12. Question 1**

In [32]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])


In [33]:
print(A)
print()
print(np.linalg.inv(A))  # inversing the 3x3 matrix

[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [34]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [35]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [36]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


The data of v2 is the part from v1 which means v2 is copy of v1. so, when you change anything in v2, it will reflect in v1 as well because they share the same data.